#!/usr/bin/env bash

DEBUG=
DIR=build/libs
INF_DIR=$DIR/inflated
FILES_DIR=$INF_DIR/BOOT-INF
MAINCLASS=hello.Application

if [ ! -z "$1" ]; then
    DEBUG="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
fi

rm -rf $INF_DIR
mkdir -p $INF_DIR

unzip $DIR/gs-rest-service-0.1.0.jar -d $INF_DIR > /dev/null

JARS=$(ls $FILES_DIR/lib)
CLASSPATH=$FILES_DIR/classes

for JAR in $JARS; do
    CLASSPATH=$CLASSPATH:$FILES_DIR/lib/$JAR
done

java -version
java $DEBUG -classpath $CLASSPATH hello.Application